feat: update helix config

diff --git a/shell/.config/shell/function b/shell/.config/shell/function
--- a/shell/.config/shell/function
+++ b/shell/.config/shell/function
@@ -18,3 +18,13 @@ y() {
 	rm -f -- "$tmp"
 }
 
+hx() {
+    if command -v helix >/dev/null 2>&1; then
+        command helix "$@"
+    elif command -v hx >/dev/null 2>&1; then
+        command \hx "$@"
+    else
+        echo "Error: Helix editor is not installed (neither 'helix' nor 'hx' found)." >&2
+        return 1
+    fi
+}
